spring.application.name=rag-qa
server.port=8001

# Error visibility
server.error.include-message=always
server.error.include-binding-errors=always

# JSP view resolver
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# The property that Spring AI AutoConfiguration is looking for
spring.ai.vectorstore.pinecone.api-key=${PINECONE_KEY}
spring.ai.vectorstore.pinecone.index-name=YOUR_VECTOR_DB

# Database connection
spring.datasource.username=YOUR_DB_USERNAME
spring.datasource.password=YOUR_DB_PASSWORD
spring.datasource.url=jdbc:mysql://localhost:3306/rag_app_db
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

spring.security.user.name=admin
spring.security.user.password=YOUR_PASSWORD
spring.security.user.roles=ADMIN

spring.mvc.hiddenmethod.filter.enabled=true
